version: 2
updates:
  - package-ecosystem: npm
    directory: /relay
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    groups:
      relay-dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /deploy/oci
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    groups:
      container-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    groups:
      workflow-actions:
        patterns:
          - "*"
